In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('/content/gurgaon_properties_missing_value_imputation.csv')

In [3]:
df.duplicated().sum()

np.int64(129)

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.head()

,property_type,society,sector,price,price_per_sqft,bedRoom,bathroom,balcony,floorNum,agePossession,built_up_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score
0,house,bestech park view aindependentda,sector 81,4.35,7937.0,4,4,3,2.0,Relatively New,5480.0,0,1,1,0,0,0,51
1,flat,signature global solera,sector 107,0.28,5680.0,2,2,2,6.0,Relatively New,543.0,0,0,0,0,0,0,45
2,flat,hcbs sports ville,sohna road,0.29,5588.0,2,2,1,4.0,Relatively New,577.0,0,0,0,0,0,0,44
3,flat,orchid petals,sector 49,2.55,12319.0,3,4,3,8.0,Relatively New,2060.0,1,0,0,0,0,1,49
4,house,signature global city,sector 37d,1.27,8089.0,3,3,3,4.0,Under Construction,1570.0,0,0,0,1,0,0,89

In [6]:
df.shape

(3558, 18)

In [7]:
train_df = df.drop(columns=['society','price_per_sqft'])

In [8]:
train_df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,floorNum,agePossession,built_up_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score
0,house,sector 81,4.35,4,4,3,2.0,Relatively New,5480.0,0,1,1,0,0,0,51
1,flat,sector 107,0.28,2,2,2,6.0,Relatively New,543.0,0,0,0,0,0,0,45
2,flat,sohna road,0.29,2,2,1,4.0,Relatively New,577.0,0,0,0,0,0,0,44
3,flat,sector 49,2.55,3,4,3,8.0,Relatively New,2060.0,1,0,0,0,0,1,49
4,house,sector 37d,1.27,3,3,3,4.0,Under Construction,1570.0,0,0,0,1,0,0,89

In [9]:
def categorize_luxury(score):
    if 0 <= score < 50:
        return "Low"
    elif 50 <= score < 150:
        return "Medium"
    elif 150 <= score <= 175:
        return "High"
    else:
        return None  # or "Undefined" or any other label for scores outside the defined bins

In [10]:
train_df['luxury_category'] = train_df['luxury_score'].apply(categorize_luxury)

In [11]:
def categorize_floor(floor):
    if 0 <= floor <= 2:
        return "Low Floor"
    elif 3 <= floor <= 10:
        return "Mid Floor"
    elif 11 <= floor <= 51:
        return "High Floor"
    else:
        return None  # or "Undefined" or any other label for floors outside the defined bins

In [12]:
train_df['floor_category'] = train_df['floorNum'].apply(categorize_floor)

In [13]:
train_df.drop(columns=['floorNum','luxury_score'],inplace=True)

In [14]:
export_df = train_df.drop(columns=['pooja room', 'store room', 'others'])

In [16]:
export_df.to_csv('gurgaon_properties_post_feature_selection_2.0.csv', index=False)