In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.svm import SVR

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor


from sklearn.decomposition import PCA

In [2]:
df=pd.read_csv('/content/gurgaon_properties_post_feature_selection_v2 (1).csv')

In [3]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor

In [4]:
df['furnishing_type'].value_counts()

furnishing_type
0.0    2349
1.0    1018
2.0     187
Name: count, dtype: int64

In [5]:
# 0 -> unfurnished
# 1 -> semifurnished
# 2 -> furnished
df['furnishing_type'] = df['furnishing_type'].replace({0.0:'unfurnished',1.0:'semifurnished',2.0:'furnished'})

In [6]:
df['servant room']=df['servant room'].astype(int)
df['store room']=df['store room'].astype(int)

In [7]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0,0,unfurnished,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1,0,unfurnished,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0,0,unfurnished,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1,0,semifurnished,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0,1,unfurnished,High,Mid Floor

In [8]:
X = df.drop(columns=['price'])
y = df['price']

In [9]:
# Applying the log1p transformation to the target variable
y_transformed = np.log1p(y)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3554 entries, 0 to 3553
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_type    3554 non-null   object
 1   sector           3554 non-null   object
 2   price            3554 non-null   float64
 3   bedRoom          3554 non-null   float64
 4   bathroom         3554 non-null   float64
 5   balcony          3554 non-null   object
 6   agePossession    3554 non-null   object
 7   built_up_area    3554 non-null   float64
 8   servant room     3554 non-null   int64
 9   store room       3554 non-null   int64
 10  furnishing_type  3554 non-null   object
 11  luxury_category  3554 non-null   object
 12  floor_category   3554 non-null   object
dtypes: float64(4), int64(2), object(7)
memory usage: 361.1+ KB

# Ordinal Encoding

In [11]:
numeric_cols = ['bedRoom','bathroom','built_up_area']
binary_cols = ['servant room','store room']
categorical_cols = ['property_type','sector','balcony','agePossession','furnishing_type','luxury_category','floor_category']

In [12]:
preprocessor_ordinal = ColumnTransformer(transformers=[('num', StandardScaler(), numeric_cols),
        ('binary','passthrough',binary_cols),
        ('ordinal', OrdinalEncoder( handle_unknown='use_encoded_value', unknown_value=-1 ), categorical_cols)],
        remainder='drop')

In [13]:
pipeline = Pipeline([
    ('preprocessor', preprocessor_ordinal),
    ('regressor', LinearRegression())
])

In [14]:
kfold = KFold( n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score( pipeline, X, y_transformed, cv=kfold, scoring='r2')
print("Mean R2:", scores.mean())
print("Std R2:", scores.std())

Mean R2: 0.7363096633436828
Std R2: 0.03238005754429933

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [16]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area']),
                                                 ('binary', 'passthrough',
                                                  ['servant room',
                                                   'store room']),
                                                 ('ordinal',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category'])])),
                ('regressor', LinearRegression())])

In [17]:
y_pred = np.expm1(pipeline.predict(X_test))

In [18]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.9463822160089357

In [19]:
def scorer(model_name, model):

    output = []

    output.append(model_name)

    pipeline = Pipeline([
        ('preprocessor', preprocessor_ordinal),
        ('regressor', model)
    ])

    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

    output.append(scores.mean())

    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

    pipeline.fit(X_train,y_train)

    y_pred = pipeline.predict(X_test)

    y_pred = np.expm1(y_pred)

    output.append(mean_absolute_error(np.expm1(y_test),y_pred))

    return output

In [20]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [21]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [22]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [23]:
model_df.sort_values(['mae'])

                 name        r2       mae
10            xgboost  0.893006  0.494470
5       random forest  0.881558  0.526437
6         extra trees  0.869282  0.543447
7   gradient boosting  0.872493  0.575806
9                 mlp  0.814658  0.729815
4       decision tree  0.768788  0.743036
8            adaboost  0.749673  0.860296
1                 svr  0.754753  0.875097
0          linear_reg  0.736310  0.946382
2               ridge  0.736314  0.946399
3               LASSO  0.059434  1.528906

# OneHotEncoding

In [24]:
preprocessor_onehot = ColumnTransformer(transformers=[('num', StandardScaler(), numeric_cols),
        ('binary','passthrough',binary_cols),
        ('onehot',OneHotEncoder(drop='first',handle_unknown='ignore',sparse_output=False),categorical_cols)],
        remainder='drop')

In [25]:
pipeline = Pipeline([
    ('preprocessor', preprocessor_onehot),
    ('regressor', LinearRegression())
])

In [26]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [27]:
scores.mean(),scores.std()

(np.float64(0.8558122985956509), np.float64(0.015558218710840512))

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [29]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area']),
                                                 ('binary', 'passthrough',
                                                  ['servant room',
                                                   'store room']),
                                                 ('onehot',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category'])])),
                ('regressor', LinearRegression())])

In [30]:
y_pred = np.expm1(pipeline.predict(X_test))

In [31]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.6483879451112142

In [32]:
def scorer(model_name, model):

    output = []

    output.append(model_name)

    pipeline = Pipeline([
        ('preprocessor', preprocessor_onehot),
        ('regressor', model)
    ])

    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

    output.append(scores.mean())

    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

    pipeline.fit(X_train,y_train)

    y_pred = pipeline.predict(X_test)

    y_pred = np.expm1(y_pred)

    output.append(mean_absolute_error(np.expm1(y_test),y_pred))

    return output

In [33]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [34]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [35]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [36]:
model_df.sort_values(['mae'])

                 name        r2       mae
10            xgboost  0.885346  0.478348
6         extra trees  0.886585  0.492733
1                 svr  0.890468  0.524561
9                 mlp  0.886865  0.528928
5       random forest  0.870692  0.538310
7   gradient boosting  0.855508  0.600026
4       decision tree  0.788744  0.633735
0          linear_reg  0.855812  0.648388
2               ridge  0.856155  0.652191
8            adaboost  0.724058  0.849662
3               LASSO -0.003598  1.576392

# OneHotEncoding With PCA

In [37]:
pipeline = Pipeline([
    ('preprocessor', preprocessor_onehot),
    ('pca', PCA(n_components=0.95)),
    ('regressor', LinearRegression())
])

In [38]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [39]:
scores.mean(),scores.std()

(np.float64(0.7774613601631328), np.float64(0.026680442427865925))

In [40]:
def scorer(model_name, model):

    output = []

    output.append(model_name)

    pipeline = Pipeline([
        ('preprocessor', preprocessor_onehot),
        ('pca', PCA(n_components=0.95)),
        ('regressor', model)
    ])

    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

    output.append(scores.mean())

    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

    pipeline.fit(X_train,y_train)

    y_pred = pipeline.predict(X_test)

    y_pred = np.expm1(y_pred)

    output.append(mean_absolute_error(np.expm1(y_test),y_pred))

    return output

In [41]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [42]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [43]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])
model_df.sort_values(['mae'])

                 name        r2       mae
6         extra trees  0.844295  0.593584
9                 mlp  0.845481  0.613173
10            xgboost  0.835542  0.626189
5       random forest  0.829392  0.630669
1                 svr  0.837736  0.642792
7   gradient boosting  0.826837  0.667025
0          linear_reg  0.777461  0.885914
2               ridge  0.777515  0.885988
8            adaboost  0.697510  0.901714
4       decision tree  0.636560  0.979523
3               LASSO -0.003598  1.576392

# Target Encoder

In [44]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.10.0-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.10.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.4/87.4 kB 2.1 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.10.0

In [45]:
import category_encoders as ce

preprocessor_target = ColumnTransformer(transformers=[ ('num', StandardScaler(), numeric_cols),
                                      ('binary','passthrough',binary_cols),
                                      ('target', ce.TargetEncoder(), categorical_cols)], remainder='drop')

In [46]:
pipeline = Pipeline([
    ('preprocessor', preprocessor_target),
    ('regressor', LinearRegression())
])

In [47]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [48]:
scores.mean(),scores.std()

(np.float64(0.826403082007084), np.float64(0.018205100345016913))

In [49]:
def scorer(model_name, model):

    output = []

    output.append(model_name)

    pipeline = Pipeline([
        ('preprocessor', preprocessor_target),
        ('regressor', model)
    ])

    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

    output.append(scores.mean())

    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

    pipeline.fit(X_train,y_train)

    y_pred = pipeline.predict(X_test)

    y_pred = np.expm1(y_pred)

    output.append(mean_absolute_error(np.expm1(y_test),y_pred))

    return output

In [50]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [51]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [52]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])
model_df.sort_values(['mae'])

                 name        r2       mae
5       random forest  0.895690  0.469233
6         extra trees  0.894537  0.473624
10            xgboost  0.897123  0.488090
7   gradient boosting  0.885508  0.528507
4       decision tree  0.801835  0.555306
9                 mlp  0.855918  0.588160
1                 svr  0.866159  0.610771
8            adaboost  0.815203  0.695069
0          linear_reg  0.826403  0.716339
2               ridge  0.826401  0.716979
3               LASSO -0.003598  1.576392

# Hybrid Encoding

In [53]:
preprocessor_hybrid = ColumnTransformer(transformers=[

        # Numerical
        ('num',StandardScaler(),numeric_cols),

        # Binary
        ('binary','passthrough',binary_cols),

        # Nominal categorical
        ('onehot', OneHotEncoder( drop='first', handle_unknown='ignore', sparse_output=False),[ 'property_type', 'agePossession', 'furnishing_type']),

        # Ordered categorical
        ('ordinal',OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1),['balcony','luxury_category','floor_category']),

        # High-cardinality categorical
        ('target',ce.TargetEncoder(), ['sector'])
    ],

    remainder='drop'
)

In [54]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor_hybrid),
    ('regressor', LinearRegression())
])

In [55]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [56]:
scores.mean(),scores.std()

(np.float64(0.828976628370946), np.float64(0.018936274205272736))

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [58]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area']),
                                                 ('binary', 'passthrough',
                                                  ['servant room',
                                                   'store room']),
                                                 ('onehot',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['property_type',
                                                   'agePossession',
                                                   'furnishing_type']),
                                                 ('ordinal',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['balcony', 'luxury_category',
                                                   'floor_category']),
                                                 ('target', TargetEncoder(),
                                                  ['sector'])])),
                ('regressor', LinearRegression())])

In [59]:
y_pred = pipeline.predict(X_test)

y_pred = np.expm1(y_pred)

mae = mean_absolute_error(np.expm1(y_test), y_pred)

print("MAE:", mae)

MAE: 0.7127278833922405

In [60]:
def scorer_hybrid(model_name, model):

    output = []

    output.append(model_name)

    pipeline = Pipeline([
        ('preprocessor', preprocessor_hybrid),
        ('regressor', model)
    ])

    # 10-Fold Cross Validation
    kfold = KFold(
        n_splits=10,
        shuffle=True,
        random_state=42
    )

    scores = cross_val_score(
        pipeline,
        X,
        y_transformed,
        cv=kfold,
        scoring='r2'
    )

    output.append(scores.mean())

    # Train-Test Split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y_transformed,
        test_size=0.2,
        random_state=42
    )

    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)

    # Convert log price to original price
    y_pred = np.expm1(y_pred)

    mae = mean_absolute_error(
        np.expm1(y_test),
        y_pred
    )

    output.append(mae)

    return output

In [61]:
hybrid_output = []

for model_name, model in model_dict.items():

    hybrid_output.append(
        scorer_hybrid(model_name, model)
    )

In [62]:
hybrid_df = pd.DataFrame(
    hybrid_output,
    columns=['name', 'r2', 'mae']
)

hybrid_df.sort_values('mae').reset_index(drop=True)

                 name        r2       mae
0       random forest  0.893504  0.468320
1         extra trees  0.892945  0.473629
2             xgboost  0.895462  0.482958
3   gradient boosting  0.883176  0.526716
4       decision tree  0.809246  0.567905
5                 svr  0.864076  0.585423
6                 mlp  0.854483  0.616814
7            adaboost  0.815312  0.690610
8          linear_reg  0.828977  0.712728
9               ridge  0.828992  0.713263
10              LASSO -0.003598  1.576392

In [63]:
!pip install optuna -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 14.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.9/265.9 kB 21.9 MB/s eta 0:00:00

In [64]:
import optuna

from sklearn.metrics import make_scorer

In [65]:
def original_scale_mae(y_true_log, y_pred_log):

    y_true = np.expm1(y_true_log)
    y_pred = np.expm1(y_pred_log)

    return mean_absolute_error(y_true, y_pred)


mae_scorer = make_scorer(
    original_scale_mae,
    greater_is_better=False
)

In [66]:
def objective(trial):

    rf = RandomForestRegressor(

        n_estimators=trial.suggest_int(
            'n_estimators', 200, 1200
        ),

        max_depth=trial.suggest_int(
            'max_depth', 5, 30
        ),

        min_samples_split=trial.suggest_int(
            'min_samples_split', 2, 15
        ),

        min_samples_leaf=trial.suggest_int(
            'min_samples_leaf', 1, 8
        ),

        max_features=trial.suggest_float(
            'max_features', 0.5, 1.0
        ),

        random_state=42,
        n_jobs=-1
    )

    pipeline = Pipeline([
        ('preprocessor', preprocessor_hybrid),
        ('regressor', rf)
    ])

    kfold = KFold(
        n_splits=5,
        shuffle=True,
        random_state=42
    )

    scores = cross_val_score(
        pipeline,
        X,
        y_transformed,
        cv=kfold,
        scoring=mae_scorer,
        n_jobs=-1
    )

    return -scores.mean()

In [68]:
study_rf = optuna.create_study(
    direction='minimize'
)

study_rf.optimize(
    objective,
    n_trials=50
)

[I 2026-08-13 05:03:59,168] A new study created in memory with name: no-name-26d7929a-0c4c-4385-aab6-de836b0725de
[I 2026-08-13 05:04:11,295] Trial 0 finished with value: 0.5078514964418641 and parameters: {'n_estimators': 281, 'max_depth': 29, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.5383665697551006}. Best is trial 0 with value: 0.5078514964418641.
[I 2026-08-13 05:04:56,737] Trial 1 finished with value: 0.5154360104079069 and parameters: {'n_estimators': 916, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.8341983603392836}. Best is trial 0 with value: 0.5078514964418641.
[I 2026-08-13 05:05:08,248] Trial 2 finished with value: 0.5219293070509892 and parameters: {'n_estimators': 388, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 0.7939029506090965}. Best is trial 0 with value: 0.5078514964418641.
[I 2026-08-13 05:05:20,651] Trial 3 finished with value: 0.5043617261052754 and parameters: {'n_estimators': 348, 'max_depth': 29, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 0.7836332808902888}. Best is trial 3 with value: 0.5043617261052754.
[I 2026-08-13 05:05:47,271] Trial 4 finished with value: 0.5292311303020737 and parameters: {'n_estimators': 1149, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 1, 'max_features': 0.5227602785874477}. Best is trial 3 with value: 0.5043617261052754.
[I 2026-08-13 05:06:05,765] Trial 5 finished with value: 0.5302577930558531 and parameters: {'n_estimators': 626, 'max_depth': 17, 'min_samples_split': 14, 'min_samples_leaf': 6, 'max_features': 0.917729109724227}. Best is trial 3 with value: 0.5043617261052754.
[I 2026-08-13 05:06:27,212] Trial 6 finished with value: 0.5257843102689692 and parameters: {'n_estimators': 819, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.6817746218912493}. Best is trial 3 with value: 0.5043617261052754.
[I 2026-08-13 05:06:48,171] Trial 7 finished with value: 0.5399176366482031 and parameters: {'n_estimators': 938, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 0.6981460516196598}. Best is trial 3 with value: 0.5043617261052754.
[I 2026-08-13 05:07:13,002] Trial 8 finished with value: 0.5467370585418376 and parameters: {'n_estimators': 1096, 'max_depth': 15, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 0.6693863200732342}. Best is trial 3 with value: 0.5043617261052754.
[I 2026-08-13 05:07:42,581] Trial 9 finished with value: 0.5210690106398175 and parameters: {'n_estimators': 1069, 'max_depth': 19, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_features': 0.7447241036073216}. Best is trial 3 with value: 0.5043617261052754.
[I 2026-08-13 05:07:59,716] Trial 10 finished with value: 0.5393915201323873 and parameters: {'n_estimators': 515, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 8, 'max_features': 0.9922470663205402}. Best is trial 3 with value: 0.5043617261052754.
[I 2026-08-13 05:08:07,741] Trial 11 finished with value: 0.49961925517452155 and parameters: {'n_estimators': 258, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 0.5064218315569042}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:08:15,248] Trial 12 finished with value: 0.5012134530340424 and parameters: {'n_estimators': 202, 'max_depth': 26, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.609886830217341}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:08:20,909] Trial 13 finished with value: 0.5231608307532674 and parameters: {'n_estimators': 245, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.5899053185154624}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:08:28,677] Trial 14 finished with value: 0.5013669281564038 and parameters: {'n_estimators': 211, 'max_depth': 25, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.6078617241515042}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:08:40,434] Trial 15 finished with value: 0.5177722873210554 and parameters: {'n_estimators': 447, 'max_depth': 25, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 0.5027598888365965}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:08:56,748] Trial 16 finished with value: 0.5138492185592364 and parameters: {'n_estimators': 603, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 0.5924234078988612}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:09:03,179] Trial 17 finished with value: 0.500215407263326 and parameters: {'n_estimators': 203, 'max_depth': 27, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.600655113998781}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:09:12,908] Trial 18 finished with value: 0.5185829843040343 and parameters: {'n_estimators': 356, 'max_depth': 28, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 0.5582361669301183}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:09:26,557] Trial 19 finished with value: 0.5346687767487864 and parameters: {'n_estimators': 554, 'max_depth': 22, 'min_samples_split': 3, 'min_samples_leaf': 6, 'max_features': 0.6374878519653736}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:09:48,267] Trial 20 finished with value: 0.5064247458385956 and parameters: {'n_estimators': 730, 'max_depth': 27, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 0.5009012594085371}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:09:54,590] Trial 21 finished with value: 0.4999386681782051 and parameters: {'n_estimators': 201, 'max_depth': 26, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.6339420654445359}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:10:04,088] Trial 22 finished with value: 0.5074042608947957 and parameters: {'n_estimators': 305, 'max_depth': 30, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.5607912659840197}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:10:18,567] Trial 23 finished with value: 0.5010196866012585 and parameters: {'n_estimators': 434, 'max_depth': 23, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 0.648989665885965}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:10:29,429] Trial 24 finished with value: 0.5035837114342352 and parameters: {'n_estimators': 292, 'max_depth': 27, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.7233641087977682}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:10:42,164] Trial 25 finished with value: 0.5137524822387984 and parameters: {'n_estimators': 458, 'max_depth': 23, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5727117610951131}. Best is trial 11 with value: 0.49961925517452155.
[I 2026-08-13 05:10:49,992] Trial 26 finished with value: 0.4976385187128371 and parameters: {'n_estimators': 219, 'max_depth': 27, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 0.6415156424675682}. Best is trial 26 with value: 0.4976385187128371.
[I 2026-08-13 05:10:56,417] Trial 27 finished with value: 0.613010410138042 and parameters: {'n_estimators': 332, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 0.6386517082380706}. Best is trial 26 with value: 0.4976385187128371.
[I 2026-08-13 05:11:12,837] Trial 28 finished with value: 0.4952343903216555 and parameters: {'n_estimators': 396, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 0.7203090472503145}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:11:27,971] Trial 29 finished with value: 0.507957818510209 and parameters: {'n_estimators': 413, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.8756664692011282}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:11:45,409] Trial 30 finished with value: 0.5022529393621246 and parameters: {'n_estimators': 502, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.7407036587627701}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:11:56,823] Trial 31 finished with value: 0.49944086283709777 and parameters: {'n_estimators': 296, 'max_depth': 28, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.7011963275876706}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:12:09,037] Trial 32 finished with value: 0.4964124030136706 and parameters: {'n_estimators': 287, 'max_depth': 29, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.7753565017791535}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:12:19,741] Trial 33 finished with value: 0.5048206372285564 and parameters: {'n_estimators': 300, 'max_depth': 28, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 0.7832488938648161}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:12:36,471] Trial 34 finished with value: 0.4981088637006472 and parameters: {'n_estimators': 388, 'max_depth': 29, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.8186209266328176}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:12:53,084] Trial 35 finished with value: 0.49817295261334904 and parameters: {'n_estimators': 386, 'max_depth': 29, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.8283082946860826}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:13:08,081] Trial 36 finished with value: 0.5008222623640284 and parameters: {'n_estimators': 379, 'max_depth': 24, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.8233561885368939}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:13:28,308] Trial 37 finished with value: 0.5154455077601588 and parameters: {'n_estimators': 600, 'max_depth': 26, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.85681388027345}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:13:46,095] Trial 38 finished with value: 0.5090623613135296 and parameters: {'n_estimators': 515, 'max_depth': 21, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.7746130837484894}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:14:16,166] Trial 39 finished with value: 0.5000141187505587 and parameters: {'n_estimators': 691, 'max_depth': 29, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 0.8790301881755157}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:14:29,793] Trial 40 finished with value: 0.5025393285489254 and parameters: {'n_estimators': 370, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 0.8080907735099699}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:14:46,572] Trial 41 finished with value: 0.49649513242916504 and parameters: {'n_estimators': 382, 'max_depth': 29, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.7567931775464453}. Best is trial 28 with value: 0.4952343903216555.
[I 2026-08-13 05:15:08,620] Trial 42 finished with value: 0.49378521310165774 and parameters: {'n_estimators': 460, 'max_depth': 29, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.7613725507086561}. Best is trial 42 with value: 0.49378521310165774.
[I 2026-08-13 05:15:26,208] Trial 43 finished with value: 0.5011716343576373 and parameters: {'n_estimators': 466, 'max_depth': 30, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.7505675485549088}. Best is trial 42 with value: 0.49378521310165774.
[I 2026-08-13 05:15:37,244] Trial 44 finished with value: 0.49553881670773575 and parameters: {'n_estimators': 260, 'max_depth': 27, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 0.7153278211925321}. Best is trial 42 with value: 0.49378521310165774.
[I 2026-08-13 05:15:48,794] Trial 45 finished with value: 0.5035281537029297 and parameters: {'n_estimators': 318, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.71128617160279}. Best is trial 42 with value: 0.49378521310165774.
[I 2026-08-13 05:16:01,653] Trial 46 finished with value: 0.5361943486897538 and parameters: {'n_estimators': 487, 'max_depth': 26, 'min_samples_split': 3, 'min_samples_leaf': 7, 'max_features': 0.7634752585186102}. Best is trial 42 with value: 0.49378521310165774.
[I 2026-08-13 05:16:22,595] Trial 47 finished with value: 0.496242850924023 and parameters: {'n_estimators': 555, 'max_depth': 24, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.6865735568850387}. Best is trial 42 with value: 0.49378521310165774.
[I 2026-08-13 05:16:38,796] Trial 48 finished with value: 0.5280373838239157 and parameters: {'n_estimators': 648, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.666015051445451}. Best is trial 42 with value: 0.49378521310165774.
[I 2026-08-13 05:16:56,089] Trial 49 finished with value: 0.5033756929215991 and parameters: {'n_estimators': 559, 'max_depth': 24, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 0.6828682116704906}. Best is trial 42 with value: 0.49378521310165774.

In [74]:
print("Best CV MAE:", study_rf.best_value)

study_rf.best_params

Best CV MAE: 0.49378521310165774

{'n_estimators': 460,
 'max_depth': 29,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 0.7613725507086561}

In [75]:
best_rf = RandomForestRegressor(
    **study_rf.best_params,
    random_state=42,
    n_jobs=-1
)

best_rf_pipeline = Pipeline([
    ('preprocessor', preprocessor_hybrid),
    ('regressor', best_rf)
])

In [76]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_transformed,
    test_size=0.2,
    random_state=42
)

In [77]:
best_rf_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area']),
                                                 ('binary', 'passthrough',
                                                  ['servant room',
                                                   'store room']),
                                                 ('onehot',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['property_type',
                                                   'agePossession',
                                                   'furnishing_type']),
                                                 ('ordinal',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['balcony', 'luxury_category',
                                                   'floor_category']),
                                                 ('target', TargetEncoder(),
                                                  ['sector'])])),
                ('regressor',
                 RandomForestRegressor(max_depth=29,
                                       max_features=0.7613725507086561,
                                       n_estimators=460, n_jobs=-1,
                                       random_state=42))])

In [78]:
y_pred = best_rf_pipeline.predict(X_test)

y_pred_original = np.expm1(y_pred)
y_test_original = np.expm1(y_test)

In [79]:
rf_mae = mean_absolute_error(
    y_test_original,
    y_pred_original
)

print("Tuned Random Forest MAE:", rf_mae)

Tuned Random Forest MAE: 0.46344225033261105

In [80]:
def objective_xgb(trial):

    xgb = XGBRegressor(

        n_estimators=trial.suggest_int(
            'n_estimators', 300, 1500
        ),

        learning_rate=trial.suggest_float(
            'learning_rate',
            0.01, 0.15,
            log=True
        ),

        max_depth=trial.suggest_int(
            'max_depth', 3, 10
        ),

        min_child_weight=trial.suggest_int(
            'min_child_weight', 1, 10
        ),

        subsample=trial.suggest_float(
            'subsample', 0.6, 1.0
        ),

        colsample_bytree=trial.suggest_float(
            'colsample_bytree', 0.6, 1.0
        ),

        reg_alpha=trial.suggest_float(
            'reg_alpha',
            1e-4, 10,
            log=True
        ),

        reg_lambda=trial.suggest_float(
            'reg_lambda',
            1e-3, 20,
            log=True
        ),

        objective='reg:squarederror',
        random_state=42,
        n_jobs=-1
    )

    pipeline = Pipeline([
        ('preprocessor', preprocessor_hybrid),
        ('regressor', xgb)
    ])

    kfold = KFold(
        n_splits=5,
        shuffle=True,
        random_state=42
    )

    scores = cross_val_score(
        pipeline,
        X,
        y_transformed,
        cv=kfold,
        scoring=mae_scorer,
        n_jobs=-1
    )

    return -scores.mean()

In [81]:
study_xgb = optuna.create_study(
    direction='minimize'
)

study_xgb.optimize(
    objective_xgb,
    n_trials=50
)

[I 2026-08-13 05:19:56,157] A new study created in memory with name: no-name-13fe2e5b-12a2-4491-bce3-4a532c4459f9
[I 2026-08-13 05:20:01,596] Trial 0 finished with value: 0.4893713001930708 and parameters: {'n_estimators': 1233, 'learning_rate': 0.0201567370733828, 'max_depth': 6, 'min_child_weight': 9, 'subsample': 0.9110464756220114, 'colsample_bytree': 0.8436395010296067, 'reg_alpha': 0.015374988535416542, 'reg_lambda': 6.4464026836082144}. Best is trial 0 with value: 0.4893713001930708.
[I 2026-08-13 05:20:03,461] Trial 1 finished with value: 0.5241978676524711 and parameters: {'n_estimators': 1125, 'learning_rate': 0.06124999882124916, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.7154670945676832, 'colsample_bytree': 0.6051504927714474, 'reg_alpha': 2.589983336212708, 'reg_lambda': 0.36039335435715586}. Best is trial 0 with value: 0.4893713001930708.
[I 2026-08-13 05:20:09,049] Trial 2 finished with value: 0.49824553761817947 and parameters: {'n_estimators': 1196, 'learning_rate': 0.03668190170787625, 'max_depth': 7, 'min_child_weight': 10, 'subsample': 0.6873457842572862, 'colsample_bytree': 0.9927882318364694, 'reg_alpha': 0.00025132474206754037, 'reg_lambda': 0.8653811573483128}. Best is trial 0 with value: 0.4893713001930708.
[I 2026-08-13 05:20:10,202] Trial 3 finished with value: 0.5357890475235487 and parameters: {'n_estimators': 766, 'learning_rate': 0.023358452772896214, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.9194861148160646, 'colsample_bytree': 0.6677036092662941, 'reg_alpha': 0.0009997850282719872, 'reg_lambda': 0.07318597113365634}. Best is trial 0 with value: 0.4893713001930708.
[I 2026-08-13 05:20:18,518] Trial 4 finished with value: 0.485400026174713 and parameters: {'n_estimators': 761, 'learning_rate': 0.0373799575058738, 'max_depth': 10, 'min_child_weight': 4, 'subsample': 0.9451599702358602, 'colsample_bytree': 0.6526312901106845, 'reg_alpha': 0.0062362554613960616, 'reg_lambda': 0.0015801030984481416}. Best is trial 4 with value: 0.485400026174713.
[I 2026-08-13 05:20:21,752] Trial 5 finished with value: 0.4852987679951616 and parameters: {'n_estimators': 642, 'learning_rate': 0.0318752362489239, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.7426057915190295, 'colsample_bytree': 0.8075839799249536, 'reg_alpha': 0.20173398981726634, 'reg_lambda': 0.10136533383429867}. Best is trial 5 with value: 0.4852987679951616.
[I 2026-08-13 05:20:26,671] Trial 6 finished with value: 0.49232052185545 and parameters: {'n_estimators': 561, 'learning_rate': 0.08882874917595149, 'max_depth': 8, 'min_child_weight': 6, 'subsample': 0.8620778714713291, 'colsample_bytree': 0.8046140783429347, 'reg_alpha': 0.09662714705698751, 'reg_lambda': 0.0027324769029813136}. Best is trial 5 with value: 0.4852987679951616.
[I 2026-08-13 05:20:41,296] Trial 7 finished with value: 0.48902258831816126 and parameters: {'n_estimators': 1422, 'learning_rate': 0.07430417023553643, 'max_depth': 10, 'min_child_weight': 2, 'subsample': 0.8056014984976687, 'colsample_bytree': 0.8575169021966966, 'reg_alpha': 0.0029891421190194898, 'reg_lambda': 0.028789399255308684}. Best is trial 5 with value: 0.4852987679951616.
[I 2026-08-13 05:20:47,065] Trial 8 finished with value: 0.4896086715707969 and parameters: {'n_estimators': 1033, 'learning_rate': 0.0189851543985943, 'max_depth': 10, 'min_child_weight': 9, 'subsample': 0.644457055201478, 'colsample_bytree': 0.9190277240760579, 'reg_alpha': 0.0011771796551616222, 'reg_lambda': 0.0035242984079031873}. Best is trial 5 with value: 0.4852987679951616.
[I 2026-08-13 05:20:52,618] Trial 9 finished with value: 0.48234572368250905 and parameters: {'n_estimators': 1269, 'learning_rate': 0.012168517057890509, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.9139365623895659, 'colsample_bytree': 0.6826493251226712, 'reg_alpha': 0.2443967519778886, 'reg_lambda': 0.008321076160937803}. Best is trial 9 with value: 0.48234572368250905.
[I 2026-08-13 05:20:53,535] Trial 10 finished with value: 0.6488442015967669 and parameters: {'n_estimators': 337, 'learning_rate': 0.010411698075516366, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.989017217693097, 'colsample_bytree': 0.7354012701239316, 'reg_alpha': 9.445808922496811, 'reg_lambda': 15.268843543016827}. Best is trial 9 with value: 0.48234572368250905.
[I 2026-08-13 05:20:58,974] Trial 11 finished with value: 0.4900002421331558 and parameters: {'n_estimators': 849, 'learning_rate': 0.010473934177060067, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7799374213681439, 'colsample_bytree': 0.7312427353023508, 'reg_alpha': 0.33810994903732905, 'reg_lambda': 0.024834680409978875}. Best is trial 9 with value: 0.48234572368250905.
[I 2026-08-13 05:21:05,910] Trial 12 finished with value: 0.48236993438629633 and parameters: {'n_estimators': 1456, 'learning_rate': 0.036996537468613686, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7874657495270374, 'colsample_bytree': 0.748228657329672, 'reg_alpha': 0.0933404592297201, 'reg_lambda': 0.012709214737820062}. Best is trial 9 with value: 0.48234572368250905.
[I 2026-08-13 05:21:13,100] Trial 13 finished with value: 0.5030850344841733 and parameters: {'n_estimators': 1488, 'learning_rate': 0.13950094139937627, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.8434539810089806, 'colsample_bytree': 0.7028565809349628, 'reg_alpha': 0.032511916363667445, 'reg_lambda': 0.009852150106125402}. Best is trial 9 with value: 0.48234572368250905.
[I 2026-08-13 05:21:18,451] Trial 14 finished with value: 0.49789479276861215 and parameters: {'n_estimators': 1315, 'learning_rate': 0.014666546951942245, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8610922678274361, 'colsample_bytree': 0.764311216879165, 'reg_alpha': 1.1491489929832441, 'reg_lambda': 0.005747005360577238}. Best is trial 9 with value: 0.48234572368250905.
[I 2026-08-13 05:21:20,933] Trial 15 finished with value: 0.4918542751501539 and parameters: {'n_estimators': 1020, 'learning_rate': 0.05135678436781924, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.6259844122589231, 'colsample_bytree': 0.6332060562237269, 'reg_alpha': 0.08013841446349819, 'reg_lambda': 0.001126973344722802}. Best is trial 9 with value: 0.48234572368250905.
[I 2026-08-13 05:21:28,305] Trial 16 finished with value: 0.48967353550165793 and parameters: {'n_estimators': 1342, 'learning_rate': 0.02838402178164598, 'max_depth': 9, 'min_child_weight': 2, 'subsample': 0.7952122997328884, 'colsample_bytree': 0.7157609277399725, 'reg_alpha': 0.8920900483587139, 'reg_lambda': 0.015638748968757565}. Best is trial 9 with value: 0.48234572368250905.
[I 2026-08-13 05:21:33,819] Trial 17 finished with value: 0.47540608460374667 and parameters: {'n_estimators': 1486, 'learning_rate': 0.0146858798102949, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9880884907449756, 'colsample_bytree': 0.7766869076233638, 'reg_alpha': 0.030297824140674442, 'reg_lambda': 0.1013350310910571}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:21:38,848] Trial 18 finished with value: 0.4816793513439109 and parameters: {'n_estimators': 1296, 'learning_rate': 0.014862156181115626, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9984338624061302, 'colsample_bytree': 0.677443337179262, 'reg_alpha': 0.018718827971897507, 'reg_lambda': 0.3501328141094258}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:21:41,283] Trial 19 finished with value: 0.4972611604811551 and parameters: {'n_estimators': 1015, 'learning_rate': 0.014702146402752239, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.9967931621439803, 'colsample_bytree': 0.7810648584983045, 'reg_alpha': 0.018233471542736395, 'reg_lambda': 1.0514860234612489}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:21:45,735] Trial 20 finished with value: 0.4779533202410068 and parameters: {'n_estimators': 1373, 'learning_rate': 0.016748239301445214, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9645254527866465, 'colsample_bytree': 0.8988337160816928, 'reg_alpha': 0.0055543060634851895, 'reg_lambda': 0.14797039430095285}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:21:51,294] Trial 21 finished with value: 0.4772518357491732 and parameters: {'n_estimators': 1383, 'learning_rate': 0.015726773876433304, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9622460482123225, 'colsample_bytree': 0.9002402529462922, 'reg_alpha': 0.005258223210099964, 'reg_lambda': 0.2120318718571441}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:21:55,878] Trial 22 finished with value: 0.4784434707861093 and parameters: {'n_estimators': 1393, 'learning_rate': 0.0185827601623858, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9472096727099842, 'colsample_bytree': 0.9194611169631621, 'reg_alpha': 0.0027104148110276573, 'reg_lambda': 0.09887678954291154}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:21:58,669] Trial 23 finished with value: 0.4886653694105159 and parameters: {'n_estimators': 1486, 'learning_rate': 0.025594530765235303, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.960517773687214, 'colsample_bytree': 0.8985547319376382, 'reg_alpha': 0.00623483259735174, 'reg_lambda': 0.27964588281613634}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:22:04,222] Trial 24 finished with value: 0.48126247176880976 and parameters: {'n_estimators': 1152, 'learning_rate': 0.01647185634658392, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8848001972656163, 'colsample_bytree': 0.9908832083930526, 'reg_alpha': 0.0001206580582055218, 'reg_lambda': 1.9891753851244387}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:22:09,911] Trial 25 finished with value: 0.48082785423849844 and parameters: {'n_estimators': 1391, 'learning_rate': 0.012495674006063228, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9632725123143011, 'colsample_bytree': 0.9449717242465128, 'reg_alpha': 0.0006194754004251018, 'reg_lambda': 0.05877947719134742}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:22:12,389] Trial 26 finished with value: 0.49602662760939537 and parameters: {'n_estimators': 1358, 'learning_rate': 0.02197134992340169, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.9320611520265875, 'colsample_bytree': 0.8664458630272481, 'reg_alpha': 0.006851285613568326, 'reg_lambda': 0.21500373512929075}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:22:19,155] Trial 27 finished with value: 0.47977806836464804 and parameters: {'n_estimators': 1083, 'learning_rate': 0.012257700768052443, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8882123830318055, 'colsample_bytree': 0.9587556945239867, 'reg_alpha': 0.04435699952406726, 'reg_lambda': 0.6609321641114386}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:22:22,038] Trial 28 finished with value: 0.4941088717008964 and parameters: {'n_estimators': 1234, 'learning_rate': 0.017313671661934114, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.9791937726311845, 'colsample_bytree': 0.8306846426596531, 'reg_alpha': 0.002278027663972582, 'reg_lambda': 3.1015862988818608}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:22:25,611] Trial 29 finished with value: 0.48131203727330424 and parameters: {'n_estimators': 1202, 'learning_rate': 0.021439939692384134, 'max_depth': 6, 'min_child_weight': 5, 'subsample': 0.8926970238995087, 'colsample_bytree': 0.8826085367937715, 'reg_alpha': 0.00630756309772708, 'reg_lambda': 0.14921412271550155}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:22:27,360] Trial 30 finished with value: 0.4997869262481571 and parameters: {'n_estimators': 922, 'learning_rate': 0.027390953414483832, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.9692647687940324, 'colsample_bytree': 0.8426289467136171, 'reg_alpha': 0.014300001009006134, 'reg_lambda': 0.040556028209774046}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:22:33,146] Trial 31 finished with value: 0.4786526299118233 and parameters: {'n_estimators': 1393, 'learning_rate': 0.019141837398265978, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.941780619942223, 'colsample_bytree': 0.9355826761119252, 'reg_alpha': 0.002819018203092703, 'reg_lambda': 0.120033341131144}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:22:37,657] Trial 32 finished with value: 0.47967439556119873 and parameters: {'n_estimators': 1406, 'learning_rate': 0.016316135407384542, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9498425090147186, 'colsample_bytree': 0.9046081925977054, 'reg_alpha': 0.0003931104260271462, 'reg_lambda': 0.5048996274361447}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:22:42,452] Trial 33 finished with value: 0.4822512699737011 and parameters: {'n_estimators': 1278, 'learning_rate': 0.013324379425945363, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.9138198858027856, 'colsample_bytree': 0.9709072070861817, 'reg_alpha': 0.0015887725044796213, 'reg_lambda': 0.14440927553335922}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:22:47,677] Trial 34 finished with value: 0.47817301527873524 and parameters: {'n_estimators': 1163, 'learning_rate': 0.019735048928486817, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9769446147637687, 'colsample_bytree': 0.8765654557808589, 'reg_alpha': 0.01126366823142397, 'reg_lambda': 0.052386063181202855}. Best is trial 17 with value: 0.47540608460374667.
[I 2026-08-13 05:22:52,873] Trial 35 finished with value: 0.47331591538898826 and parameters: {'n_estimators': 1146, 'learning_rate': 0.02338113889216173, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.97285368437607, 'colsample_bytree': 0.8249995774808797, 'reg_alpha': 0.011003164357885927, 'reg_lambda': 0.05373107321813057}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:22:58,761] Trial 36 finished with value: 0.4764665165874389 and parameters: {'n_estimators': 1098, 'learning_rate': 0.04563940831115176, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.9271073538404759, 'colsample_bytree': 0.8172636736755277, 'reg_alpha': 0.036308687155059985, 'reg_lambda': 1.4025203138355595}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:23:07,228] Trial 37 finished with value: 0.4847228440624721 and parameters: {'n_estimators': 1085, 'learning_rate': 0.04807052167539718, 'max_depth': 9, 'min_child_weight': 1, 'subsample': 0.922326241623816, 'colsample_bytree': 0.8061059467179968, 'reg_alpha': 0.042957969702174394, 'reg_lambda': 1.3922378728342564}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:23:13,807] Trial 38 finished with value: 0.4839879662638672 and parameters: {'n_estimators': 955, 'learning_rate': 0.09913076786764731, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8982616997647133, 'colsample_bytree': 0.7862744711550104, 'reg_alpha': 0.030639201423747483, 'reg_lambda': 5.353291462329514}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:23:19,685] Trial 39 finished with value: 0.47539700357429987 and parameters: {'n_estimators': 1218, 'learning_rate': 0.03187614729110534, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8319203563868675, 'colsample_bytree': 0.8240162630865048, 'reg_alpha': 0.06643316152371027, 'reg_lambda': 0.028910603186418613}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:23:25,594] Trial 40 finished with value: 0.4789158086932942 and parameters: {'n_estimators': 1101, 'learning_rate': 0.043423138705135186, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8193933986656544, 'colsample_bytree': 0.819608060552159, 'reg_alpha': 0.16633002015882314, 'reg_lambda': 0.02907915600788744}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:23:31,689] Trial 41 finished with value: 0.477669909135809 and parameters: {'n_estimators': 1203, 'learning_rate': 0.030452133437540663, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7567156156081921, 'colsample_bytree': 0.8484618641917903, 'reg_alpha': 0.07303613501021894, 'reg_lambda': 0.06542572134645043}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:23:37,421] Trial 42 finished with value: 0.486746928298096 and parameters: {'n_estimators': 1248, 'learning_rate': 0.05854079444378196, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.6788313828764206, 'colsample_bytree': 0.7855093174751806, 'reg_alpha': 0.43859572943136416, 'reg_lambda': 0.01741357137763236}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:23:42,341] Trial 43 finished with value: 0.49097274587669587 and parameters: {'n_estimators': 1125, 'learning_rate': 0.032987028175208225, 'max_depth': 7, 'min_child_weight': 10, 'subsample': 0.8698114027261601, 'colsample_bytree': 0.8315452319739288, 'reg_alpha': 0.01066766276862745, 'reg_lambda': 19.09853628851969}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:23:47,574] Trial 44 finished with value: 0.48265717867748953 and parameters: {'n_estimators': 953, 'learning_rate': 0.04326862498269012, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.8239626091554771, 'colsample_bytree': 0.8121203914943123, 'reg_alpha': 0.13875122688450908, 'reg_lambda': 0.2532084720317336}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:23:55,528] Trial 45 finished with value: 0.4793996822500414 and parameters: {'n_estimators': 1454, 'learning_rate': 0.024224616103586453, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7110626814257963, 'colsample_bytree': 0.7689290716298396, 'reg_alpha': 0.028294189377041663, 'reg_lambda': 0.6181527828956385}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:23:59,276] Trial 46 finished with value: 0.48604247290665253 and parameters: {'n_estimators': 864, 'learning_rate': 0.035722502710600415, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.9271623745466203, 'colsample_bytree': 0.7557265372915007, 'reg_alpha': 0.019680420860700328, 'reg_lambda': 0.034165157993538135}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:24:06,924] Trial 47 finished with value: 0.4883629612823208 and parameters: {'n_estimators': 1314, 'learning_rate': 0.0696589198839406, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.984109472840512, 'colsample_bytree': 0.8626326510279465, 'reg_alpha': 0.05157688572542507, 'reg_lambda': 7.8825409908163175}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:24:09,046] Trial 48 finished with value: 0.481571106239948 and parameters: {'n_estimators': 574, 'learning_rate': 0.04081801878584739, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.905953623283377, 'colsample_bytree': 0.825141617627043, 'reg_alpha': 0.00395369520914335, 'reg_lambda': 0.08603219215338016}. Best is trial 35 with value: 0.47331591538898826.
[I 2026-08-13 05:24:13,341] Trial 49 finished with value: 0.47750293957085804 and parameters: {'n_estimators': 1179, 'learning_rate': 0.02418237044438676, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.8444550302201425, 'colsample_bytree': 0.8030366689733252, 'reg_alpha': 0.008760203777041856, 'reg_lambda': 0.005112439648110853}. Best is trial 35 with value: 0.47331591538898826.

In [82]:
print("Best XGBoost CV MAE:", study_xgb.best_value)

study_xgb.best_params

Best XGBoost CV MAE: 0.47331591538898826

{'n_estimators': 1146,
 'learning_rate': 0.02338113889216173,
 'max_depth': 7,
 'min_child_weight': 1,
 'subsample': 0.97285368437607,
 'colsample_bytree': 0.8249995774808797,
 'reg_alpha': 0.011003164357885927,
 'reg_lambda': 0.05373107321813057}

In [83]:
best_xgb = XGBRegressor(
    **study_xgb.best_params,
    objective='reg:squarederror',
    random_state=42,
    n_jobs=-1
)

best_xgb_pipeline = Pipeline([
    ('preprocessor', preprocessor_hybrid),
    ('regressor', best_xgb)
])

In [84]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_transformed,
    test_size=0.2,
    random_state=42
)

best_xgb_pipeline.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area']),
                                                 ('binary', 'passthrough',
                                                  ['servant room',
                                                   'store room']),
                                                 ('onehot',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['property_type',
                                                   'agePossession',
                                                   'furnishing_type']),
                                                 ('ordinal',
                                                  OrdinalEncoder(handle_u...
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None,
                              learning_rate=0.02338113889216173, max_bin=None,
                              max_cat_threshold=None, max_cat_to_onehot=None,
                              max_delta_step=None, max_depth=7, max_leaves=None,
                              min_child_weight=1, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=1146, n_jobs=-1,
                              num_parallel_tree=None, ...))])

In [85]:
y_pred_xgb = best_xgb_pipeline.predict(X_test)

xgb_mae = mean_absolute_error(
    np.expm1(y_test),
    np.expm1(y_pred_xgb)
)

print("Tuned XGBoost MAE:", xgb_mae)

Tuned XGBoost MAE: 0.4428102832873327

In [86]:
# Convert back to original price scale
actual_price = np.expm1(y_test)
predicted_price = np.expm1(y_pred_xgb)

error_df = X_test.copy()

error_df['actual_price'] = actual_price.values
error_df['predicted_price'] = predicted_price

error_df['absolute_error'] = abs(
    error_df['actual_price'] -
    error_df['predicted_price']
)

error_df.head()

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category,actual_price,predicted_price,absolute_error
299,flat,sector 90,4.0,4.0,3+,Moderately Old,2005.0,1,0,unfurnished,Low,High Floor,1.70,1.703106,0.003106
2240,flat,sector 92,2.0,2.0,2,New Property,1083.0,0,0,semifurnished,Low,Low Floor,0.78,0.758386,0.021614
2384,flat,sector 37d,3.0,3.0,2,Under Construction,1439.0,0,0,unfurnished,Low,Low Floor,1.10,1.238161,0.138161
3473,house,sector 23,4.0,4.0,2,Old Property,3078.0,0,0,unfurnished,Low,Low Floor,5.00,5.481075,0.481075
2614,flat,sector 102,4.0,5.0,3+,Moderately Old,2311.0,1,0,unfurnished,Medium,High Floor,2.65,2.553311,0.096689

In [87]:
error_df.groupby('property_type')['absolute_error'].agg(
    ['count', 'mean', 'median']
)

               count      mean    median
property_type
flat             573  0.270308  0.133691
house            138  1.159069  0.588352

In [88]:
error_df.sort_values(
    'absolute_error',
    ascending=False
).head(20)

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category,actual_price,predicted_price,absolute_error
1271,house,sector 43,7.0,8.0,3+,Old Property,9000.0,1,1,semifurnished,Low,Mid Floor,11.50,22.819317,11.319317
3066,house,sector 60,9.0,12.0,3+,Relatively New,6390.0,1,0,semifurnished,Medium,Mid Floor,18.02,7.088709,10.931291
2860,house,sector 25,6.0,5.0,2,Relatively New,6000.0,0,0,unfurnished,Low,Mid Floor,16.00,6.204030,9.795970
76,flat,sector 48,4.0,4.0,3+,Moderately Old,3831.0,1,1,semifurnished,Medium,Mid Floor,9.30,4.465716,4.834284
985,house,sector 43,9.0,9.0,3+,Moderately Old,3510.0,1,0,unfurnished,Low,Mid Floor,14.00,9.378872,4.621128
1655,house,sector 50,5.0,7.0,2,Moderately Old,7000.0,1,0,furnished,Low,Mid Floor,10.00,14.109781,4.109781
3044,house,sector 26,5.0,4.0,3+,Moderately Old,4518.0,1,1,semifurnished,Medium,Mid Floor,18.00,14.088240,3.911760
1295,flat,sector 54,3.0,3.0,3,Moderately Old,1382.0,0,0,unfurnished,Low,Low Floor,5.70,1.979159,3.720841
3307,flat,sector 48,5.0,6.0,3+,Relatively New,7444.0,1,0,furnished,Low,High Floor,15.00,11.358463,3.641537
443,flat,sector 106,5.0,6.0,3+,Under Construction,3797.0,0,0,semifurnished,Medium,Mid Floor,6.30,2.742476,3.557524
718,house,sohna road,3.0,3.0,3+,Moderately Old,3500.0,1,0,unfurnished,Low,Low Floor,5.50,2.001827,3.498173
322,house,sector 28,4.0,4.0,0,Relatively New,3240.0,0,0,unfurnished,Low,Mid Floor,4.50,7.856133,3.356133
554,house,sector 26,3.0,3.0,3,Old Property,8829.0,0,0,unfurnished,Medium,Low Floor,3.25,6.564905,3.314905
1677,house,sector 43,5.0,5.0,3+,Relatively New,2700.0,1,0,semifurnished,Low,Mid Floor,7.00,10.267519,3.267519
1356,house,sector 109,4.0,5.0,3+,Relatively New,7000.0,0,0,semifurnished,Medium,Low Floor,6.30,9.457377,3.157377
505,house,sector 66,5.0,6.0,3+,Relatively New,4500.0,1,1,furnished,High,Mid Floor,18.00,14.882074,3.117926
2467,house,sector 109,5.0,7.0,3+,Relatively New,6228.0,1,1,unfurnished,Medium,Mid Floor,6.25,9.186361,2.936361
1962,house,sector 72,4.0,5.0,3+,Relatively New,7000.0,0,0,semifurnished,Low,Mid Floor,8.60,5.692879,2.907121
2236,flat,sector 48,3.0,3.0,3+,Moderately Old,2364.0,1,0,furnished,Medium,Mid Floor,5.15,2.369699,2.780301
969,house,sector 13,4.0,5.0,2,Old Property,4950.0,0,0,unfurnished,Low,Low Floor,4.50,7.210499,2.710499

In [89]:
error_df.groupby('property_type')['absolute_error'].agg(
    count='count',
    mean_mae='mean',
    median_error='median',
    max_error='max'
)

               count  mean_mae  median_error  max_error
property_type
flat             573  0.270308      0.133691   4.834284
house            138  1.159069      0.588352  11.319317

In [90]:
error_df['price_range'] = pd.cut(
    error_df['actual_price'],
    bins=[0, 1, 2, 3, 5, 10, np.inf],
    labels=[
        '<1 Cr',
        '1-2 Cr',
        '2-3 Cr',
        '3-5 Cr',
        '5-10 Cr',
        '10+ Cr'
    ]
)

error_df.groupby(
    'price_range',
    observed=True
)['absolute_error'].agg(
    ['count', 'mean', 'median']
)

             count      mean    median
price_range
<1 Cr          202  0.145560  0.092163
1-2 Cr         264  0.208714  0.130619
2-3 Cr          97  0.375307  0.256721
3-5 Cr          61  0.771038  0.591553
5-10 Cr         65  1.209415  0.921398
10+ Cr          22  3.103836  2.261167